// 文件名: app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// --- 🚀 关键：你是否导入了这一行？ ---
import { ContextProvider } from './providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Ultimate DApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* --- 🚀 关键：你是否在这里“包裹”了 children？ --- */}
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}